name: cv_template
description: "A project to create a nice looking CV."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  syntax_highlight: ^0.4.0
  timelines: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
